#!/usr/bin/env bash

# heroku will override $PS1 when specified as a config var, so we'll set it here to make the jupyter
# terminal interface a little prettier:
export PS1='\[\033[01;34m\]\w\[\033[00m\]\$'

echo "Starting Jupyter ${JUPYTER_NOTEBOOK_OR_LAB}"

# Determine the correct command
# Default to 'lab' if JUPYTER_NOTEBOOK_OR_LAB is not set or is 'notebook'
# as we are focusing on JupyterLab for this setup.
JUPYTER_COMMAND="lab"
if [ "$JUPYTER_NOTEBOOK_OR_LAB" = "jupyterhub-singleuser" ]; then
    JUPYTER_COMMAND="jupyterhub-singleuser"
# elif [ "$JUPYTER_NOTEBOOK_OR_LAB" = "notebook" ]; then
# JUPYTER_COMMAND="notebook" # Could also default to lab here too
fi

# Start JupyterLab, explicitly setting the notebook directory
# to /app/notebooks where main.ipynb will be located.
# The /app directory is the root of your Heroku slug.
echo "Launching: jupyter $JUPYTER_COMMAND --notebook-dir=/app/notebooks ..."
jupyter $JUPYTER_COMMAND \
    --notebook-dir=/app/notebooks \
    --no-browser --ip=0.0.0.0 --port=$PORT \
    --ServerApp.allow_origin='*' --ServerApp.allow_credentials=True \
    $JUPYTER_NOTEBOOK_ARGS
